### ISSUE TITLE
Anyone else suddenly getting error 500: Internal Server Error?

### ISSUE THREAD

**Issue by mjmmagic** [fillup/walmart-partner-api-sdk-php#49]
My script for importing orders was working fine yesterday (and for months prior).   Suddenly today, I am getting this when I call it:

> C:\Users\Jeff\Downloads\php>php jeffWalmart.php importorders
> PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error response [url] https://marketplace.walmartapis.com/v3/orders/released?limit=10&createdStartDate=2017-03-23 [status code] 500 [reason phrase] Internal Server Error' in C:\Users\Jeff\Downloads\php\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:89
> Stack trace:
> #0 C:\Users\Jeff\Downloads\php\vendor\guzzlehttp\guzzle\src\Subscriber\HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
> #1 C:\Users\Jeff\Downloads\php\vendor\guzzlehttp\guzzle\src\Event\Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
> #2 C:\Users\Jeff\Downloads\php\vendor\guzzlehttp\guzzle\src\RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
> #3 C:\Users\Jeff\Downloads\php\vendor\guzzlehttp\guzzle\src\RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Obj in C:\Users\Jeff\Downloads\php\vendor\guzzlehttp\command\src\AbstractClient.php on line 171

Since nothing changed on my end, I am wondering if this Internal Server Error is happening with others.

**Comment by mjmmagic** [comment]
Now it seems to work again......must have been an issue on Walmart's side.
